name: Big Query Costs
description: >-
  Shows the total unique jobs ran by BigQuery, and the number of GBs scanned by
  those jobs.
tableName: big_query_jobs
updatedAt: "2025-01-01T00:00:00.000Z"
metricQuery:
  exploreName: big_query_jobs
  dimensions:
    - big_query_jobs_creation_time_week
  metrics:
    - big_query_jobs_total_bytes_processed_total_bytes_billed
  filters:
    dimensions:
      id: 1885ca54-f56e-4c23-8a1c-590171d7e7d4
      and:
        - id: 9c70204e-48c3-4f5e-8a5e-0c7890e5190c
          target:
            fieldId: big_query_jobs_creation_time_day
          values:
            - 0
          operator: notInTheCurrent
          required: false
          settings:
            completed: false
            unitOfTime: days
  sorts:
    - fieldId: big_query_jobs_creation_time_week
      descending: true
  limit: 500
  metricOverrides: {}
  tableCalculations:
    - name: cost
      displayName: Cost
      sql: >-
        (${big_query_jobs.total_bytes_processed_total_bytes_billed}/1000000000000)
        * 6.5
      format:
        type: currency
        currency: USD
        separator: default
      type: number
  additionalMetrics:
    - name: job_id_count_of_jobs
      label: Count of Jobs
      description: "Count distinct of Job id on the table Big query costs "
      sql: ${TABLE}.job_id
      table: big_query_jobs
      type: count_distinct
      baseDimensionName: job_id
      formatOptions:
        type: default
        separator: default
    - name: total_bytes_processed_total_bytes_billed
      label: Total bytes billed
      description: "Sum of Total bytes processed on the table Big query costs "
      sql: ${TABLE}.total_bytes_processed
      table: big_query_jobs
      type: sum
      baseDimensionName: total_bytes_processed
      formatOptions:
        type: default
        separator: default
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: big_query_jobs_creation_time_week
      yField:
        - cost
      flipAxes: false
      showGridX: false
    eChartsConfig:
      yAxis:
        - name: ""
        - name: ""
      legend:
        show: false
        type: plain
        orient: horizontal
      series:
        - type: bar
          label:
            show: true
            position: top
          encode:
            xRef:
              field: big_query_jobs_creation_time_week
            yRef:
              field: cost
          yAxisIndex: 0
dashboardSlug: ld-bq-bigquery-usage-tracking
spaceSlug: templates
slug: ld-bq-big-query-costs
tableConfig:
  columnOrder:
    - big_query_jobs_creation_time_week
    - big_query_jobs_total_bytes_processed_total_bytes_billed
    - cost
version: 1
